### PR TITLE
PRIS-151: Added support for meta-data

### PR DESCRIPTION
**Pull request by christianpape**
* JIRA: https://issues.opennms.org/browse/PRIS-151

Upgraded model version to 24.1.3 and enhanced XLS and JDBC source to support node-level meta-data.

### CODE REVIEW

**Comment by mfuhrmann** [comment]
It seems not to work in my tests.

XLS column: `MetaData_Credentials`
Value: `pguser:password`

PRIS does not show MetaData: 
image

**Comment by christianpape** [comment]
I tried again and it worked for me. Did you checked out this branch and made a clean build?

**Comment by christianpape** [comment]
Bildschirmfoto 2019-09-30 um 13 22 11

**Comment by mfuhrmann** [comment]
Good question. I'm using this one: https://hub.docker.com/layers/opennms/pris/1.1.7-b557/images/sha256-c1f8f4514759712023d86abf452062a84cd79134eaf0169bfb81f7a3b9727556

**Comment by indigo423** [comment]
> Good question. I'm using this one: https://hub.docker.com/layers/opennms/pris/1.1.7-b557/images/sha256-c1f8f4514759712023d86abf452062a84cd79134eaf0169bfb81f7a3b9727556

You have to use the docker image from his build: https://circleci.com/gh/OpenNMS/opennms-provisioning-integration-server/589#artifacts/containers/0

**Comment by indigo423** [comment]
@mfuhrmann the branch is built with CircleCI, If you expand the "All checks have passed" you will see the step which generates the Docker OCI image as an artifact. You can download the OCI image from this build step from the "Artifacts" tab when you click on "Details". We do not publish every change to DockerHub. We push only on DockerHub when we make releases.

**Comment by mfuhrmann** [comment]
Makes sense. I think I mixed up some URLs, names whatever...
Let's give a try again.

**Comment by mfuhrmann** [comment]
@christianpape I've tested again and it worked perfectly! Thanks!

snippet from PRIS requisition: `<meta-data context="requisition" key="Credentials" value="pguser:password"/>`
ONMS node page: 
image

**Pull request merged**
